[colors.primary]
background = "#F8F6F1" # soft ivory paper
foreground = "#2E2E2E" # ink charcoal

[colors.normal]
black = "#4A4A4A"   # graphite
red = "#C95E4A"     # inked red accent
green = "#549E6A"   # same pleasant green from yours
yellow = "#BDA24C"  # muted gold
blue = "#509475"    # teal-blue
magenta = "#C6789E" # gentle magenta
cyan = "#2DD5B7"    # fresh cyan accent
white = "#E8E5D7"   # aged paper white

[colors.bright]
black = "#6A6A6A"
red = "#E68A78"
green = "#63B07A"
yellow = "#E5C736"
blue = "#79B8A3"
magenta = "#D48FB3"
cyan = "#8CD3CB"
white = "#F8F6F1"

[colors.cursor]
text = "#F8F6F1"
cursor = "#509475" # teal ink cursor
