[colors.primary]
background = "#F8F6F1"
foreground = "#2E2E2E"

[colors.normal]
black = "#4A4A4A"
red = "#C95E4A"
green = "#4A4A4A"
yellow = "#BDA24C"
blue = "#509475"
magenta = "#C6789E"
cyan = "#2DD5B7"
white = "#E8E5D7"

[colors.bright]
black = "#6A6A6A"
red = "#E68A78"
green = "#6A6A6A"
yellow = "#E5C736"
blue = "#79B8A3"
magenta = "#D48FB3"
cyan = "#8CD3CB"
white = "#F8F6F1"

[colors.cursor]
text = "#F8F6F1"
cursor = "#2E2E2E"
